### ISSUE TITLE
How do I get in contact with you ?

### ISSUE THREAD

**Issue by thewisejun** [gurdeep999/reverseDisperse#1]
Hey gurdeep, long time we've worked together its been 2 years, I'd like to get in contact with you , 

marketing@contentmatch.io

I also have a discord , I want to speak again. reply if you see this , I hope you're doing good

**Comment by gurdeep999** [comment]
Hey man, Gurdeep#6477

> Hey gurdeep, long time we've worked together its been 2 years, I'd like to get in contact with you ,
> 
> [marketing@contentmatch.io](mailto:marketing@contentmatch.io)
> 
> I also have a discord , I want to speak again. reply if you see this , I hope you're doing good

yo wisejun, can't believe its been that long. Good to hear from you.
Just hit me up on discord- Gurdeep#6477
